[package]
name = "pintora"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Min Chen (hikerpig)","Taylorh140"]
license = "MIT"
description = "Package to draw Sequence Diagrams, Entity Relationship Diagrams, Component Diagrams, Activity Diagrams, Mind Maps, Gantt Diagrams, and DOT Diagrams"

homepage = "https://github.com/taylorh140/typst-pintora"
repository = "https://github.com/taylorh140/typst-pintora"
keywords = [
    "js",
    "javascript",
    "pintora",
    "gantt",
    "sequence",
]
exclude = [
    "pintora.svg"
]
